/*      Important points related to Inheritance 
Increases reusability of program .
In C++ , we can reuse and add additional information code . 
Reusing classes saves time and memory . 
Reusing already tested and debugged class will save lot of time and effort .
We can use the properties of a class by inheriting it .
The existing class is called as BASE CLASS .
The new class which is inherited is called DERIVED CLASS .
        Types of inheritance 
    1) Single inheritance - A derived class with only one base class .  
    2) Multiple inheritance - A derived class with more than one BASE class .
    3) Hierarchial inheritance - Several derived class from a single BASE class .
    4) MUltilevel inheritance - Deriving a class from already derived class . 
    5) Hybrid inheritance - Combination of multiple and multilevel inheritance .
*/
