/*
INTRODUCTION TO STL(Standard template Library)
    Limited time -> Resize,Sort,Search
    Library of what ? -->It is a generic classes and functions.
    Why use STL? ->Reuse of well tested functions .
                 ->Saves Time.
    Components of STL ? 
        Containers (1.Stores Data , 2.Use template classes)
        Algorithms (Sorting,Searching,etc by using template function )
        Iterators (It is an object which points to an element in a container , Handled just like pointers )
                       
*/