/*
STL= Containers + Algorithms + Iterators
    Containers -Object which stores data 
    Algorithms -Procedure to process Data 
    Iterators -Object which points to an element of a container

    There are 3 types of Containers :
    1)Sequence containers - Stores data in linear fashion . eg: vector,list,dequeue
    2)Associative containers - Gives direct access . eg:set,multi=st,map,multi-map,etc
    2)Derived containers - Derived from sequence or associative containers. Real world modelling 
         eg:Stack,queue,priority queue

     Which to use when ?
     Sequence containers-
     Vector-Random access is very fast , Insertion/deletion is slow .
     List - Random access is slow , middle/end insertion is fast .

     Associative containers - All operation are fast except random access .

     Derived containers- Depends-Data Structure.   

*/
#include<iostream>
using namespace std;

int main()
{

    return 0;
}